# Playbook for Web Server Set-Up

- hosts: "{{ override_hosts | default('live') }}"

  vars_files:
    - vars/default.yml
    - vars/parameters.private.yml

  vars:
    app_environment: "live"
    ansible_user: "{{ server_user }}"
    docker_env_root: "{{ app_root }}/server/docker/env"

  tasks:
    # Manage Services
    - import_tasks: ./custom/tasks/stop-services.yml

    # Project Set-Up (App & Cockpit)
    - import_tasks: ./custom/tasks/set-up-app.yml
    - import_tasks: ./custom/tasks/set-up-cockpit.yml

    # Certificates
    - import_tasks: ./shared/tasks/set-up-certificates.yml
    - import_tasks: ./custom/tasks/set-up-certificate-crontab.yml

    # Manage Services
    - import_tasks: ./custom/tasks/start-services.yml

    # Listener
    - import_tasks: ./shared/tasks/set-up-listener-service.yml
    - import_tasks: ./custom/tasks/set-up-listener-config.yml
