# Playbook for System Set-Up

- hosts: "{{ override_hosts | default('live') }}"

  vars_files:
    - vars/foundation.yml

  vars:
    ansible_user: "{{ server_user }}"

  tasks:
    - import_tasks: ./shared/tasks/set-up-swift.yml
    - import_tasks: ./shared/tasks/set-up-cockpit-sync.yml
    #- import_tasks: ./shared/tasks/set-up-listener.yml
