# Playbook for Web Server Set-Up

- hosts: "{{ override_hosts | default('live') }}"

  vars_files:
    - vars/default.yml
    - vars/parameters.private.yml
    
  vars:
    app_environment: "live"
    ansible_user: "{{ server_user }}"
    docker_env_root: "{{ app_root }}/server/docker/env"

  tasks:
    - import_tasks: ./custom/tasks/stop-services-live.yml
    - import_tasks: ./custom/tasks/set-up-app.yml
    - import_tasks: ./custom/tasks/set-up-cockpit.yml
    - import_tasks: ./shared/tasks/set-up-certificates.yml
    - import_tasks: ./custom/tasks/start-services-live.yml
    - import_tasks: ./custom/tasks/set-up-gitlab-listener-configuration.yml