# Variables

# "APP_STARTUP_CMD"                     Start-up command invoked for App service after setting up dependencies. Example "yarn dev"

version: "3.9"

services:
  app:
    container_name: freytag_app
    image: node:16.4.2
    volumes:
      - ./${APP_ROOT}:/var/app:cached
      - data_app_node_modules:/var/app/node_modules
      - data_app_build_framework:/var/app/.next
    working_dir: /var/app
    command: ${APP_STARTUP_CMD}
    networks:
      - dropship_shared
    ports:
      - 9229:9229
    depends_on:
      app_dependencies:
        condition: service_completed_successfully
    restart: unless-stopped

  app_dependencies:
    container_name: freytag_app_dependencies
    image: node:16.4.2
    volumes:
      - ./${APP_ROOT}/package.json:/var/app/package.json
      - ./${APP_ROOT}/yarn.lock:/var/app/yarn.lock
      - data_app_node_modules:/var/app/node_modules
    working_dir: /var/app
    command: yarn

  cockpit:
    container_name: freytag_cockpit
    image: agentejo/cockpit:latest
    volumes:
      - data_cockpit:/var/www/html/storage
    networks:
      - dropship_shared
    environment:
      - COCKPIT_SESSION_NAME=cockpit
    restart: unless-stopped

volumes:
  data_cockpit:
    driver: local
  data_app_node_modules:
    driver: local
  data_app_build_framework:
    driver: local

networks:
  dropship_shared:
    external: true