# Variables

# "APP_ENVIRONMENT"                     Active environment for services to operate in. Example: "LIVE", "DEV"
# "APP_STARTUP_CMD"                     Start-up command invoked for App service after setting up dependencies. Example "yarn dev"
# "COCKPIT_ACCESS_TOKEN"                Private access token used to authenticate with Cockpit to read data.
# "COCKPIT_PROTOCOL"                    The network protocol used to communicate with Cockpit in the current environment. Example "https"
# "COCKPIT_HOST_CLIENT"                 The Cockpit hostname used and expected to be reachable on the client-side.
# "COCKPIT_HOST_SERVER"                 The Cockpit hostname used and expected to be reachable on the server-side.
# "SERVER_NGINX_CONFIG_FILE"            NGINX configuration file name, mapped into the NGINX container. Example: "nginx.dev.conf"
# "SERVER_CERTIFICATE_DIRECTORY"        Path to the server's local certificate directory (not in container).
# "SERVER_CERTIFICATE_LOG_DIRECTORY"    Path to the server's local certificate log output directory (not in container).

version: "3.9"

services:
  proxy:
    container_name: freytag_proxy
    build:
      context: ./server/docker
      dockerfile: nginx.dockerfile
    image: custom-nginx
    volumes:
      - ./server/nginx/${SERVER_NGINX_CONFIG_FILE}:/etc/nginx/nginx.conf:cached
      - ./server/nginx/include:/etc/nginx/include:cached
      - ${SERVER_CERTIFICATE_DIRECTORY}:/etc/letsencrypt:cached
      - ${SERVER_CERTIFICATE_LOG_DIRECTORY}:/var/log/letsencrypt:cached
      - data_app_build_generated:/usr/share/nginx/html/build
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on: 
      - app
      - cockpit

  app:
    container_name: freytag_app
    image: node:15.14.0
    volumes:
      - ./app-next:/var/app:cached
      - data_app_node_modules:/var/app/node_modules
      - data_app_build_framework:/var/app/.next
    working_dir: /var/app
    command: "${APP_STARTUP_CMD}"
    depends_on:
      app-dependencies:
        condition: service_completed_successfully
    restart: unless-stopped

  app-dependencies:
    container_name: freytag_app_dependencies
    image: node:15.14.0
    volumes:
      - ./app-next/package.json:/var/app/package.json:cached
      - data_app_node_modules:/var/app/node_modules
    working_dir: /var/app
    command: "yarn"

  cockpit:
    container_name: freytag_cockpit
    image: agentejo/cockpit:0.11.2
    volumes:
      - data_cockpit:/var/www/html/storage
    restart: unless-stopped
    environment:
      - COCKPIT_SESSION_NAME=cockpit

volumes:
  data_cockpit:
    driver: local
  data_app_node_modules:
    driver: local
  data_app_build_framework:
    driver: local
  data_app_build_generated:
    driver: local
