# Variables

# "APP_ROOT"                           The root directory to mount for the app.
# "APP_STARTUP_CMD"                    Start-up command invoked for app service after setting up dependencies. Example "yarn dev"

version: "3.9"

services:
  app:
    build:
      context: ./server/docker/images/app
    image: freytag/app
    volumes:
      - ./package.json:/var/app/package.json:ro
      - ./tsconfig.json:/var/app/tsconfig.json:ro
      - ./tsconfig.packages.json:/var/app/tsconfig.packages.json:ro
      - ./app-common:/var/app/app-common
      - ./app-next:/var/app/app-next
      - ./yarn.lock:/var/app/yarn.lock:ro
      - data-app-modules:/var/app/node_modules:ro
      - data-app-framework-cache:/var/app/app-next/.next
      - data-app-themes:/var/themes:ro
    working_dir: /var/app
    command: ${APP_STARTUP_CMD}
    networks:
      - default
      - dropship-shared
    ports:
      - 9229:9229
    depends_on:
      app-dependencies:
        condition: service_completed_successfully
    restart: unless-stopped

  app-dependencies:
    build:
      context: ./server/docker/images/app
    image: freytag/app
    volumes:
      - ./package.json:/var/app/package.json:ro
      - ./app-common:/var/app/app-common:ro
      - ./app-next:/var/app/app-next:ro
      - ./yarn.lock:/var/app/yarn.lock
      - data-app-modules:/var/app/node_modules
    working_dir: /var/app
    command: yarn --verbose

  app-content:
    image: flashspys/nginx-static
    volumes:
      - data-app-themes:/static/themes:ro
    networks:
      - default
    restart: unless-stopped

  cron:
    build:
      context: ./server/docker/images/cron
    image: freytag/cron
    volumes:
      - ./server/crontabs:/etc/crontabs:ro
    networks:
      - default
    restart: unless-stopped

  color-theme-utility:
    build:
      context: ./server/docker/images/color-theme-utility
      args:
        - COLOR_THEME_UTILITY_URL=${COLOR_THEME_UTILITY_URL}
    image: freytag/color-theme-utility
    volumes:
      - data-app-themes:/var/themes
    networks:
      - default
    restart: unless-stopped

  cockpit:
    image: agentejo/cockpit:latest
    volumes:
      - data-cockpit:/var/www/html/storage
    networks:
      - default
      - dropship-shared
    environment:
      - COCKPIT_SESSION_NAME=cockpit
    restart: unless-stopped

volumes:
  data-cockpit:
    name: freytag-data-cockpit
    driver: local
  data-app-modules:
    name: freytag-data-app-modules
    driver: local
  data-app-framework-cache:
    name: freytag-data-app-framework-cache
    driver: local
  data-app-themes:
    name: freytag-data-app-themes
    driver: local

networks:
  default:
    name: freytag-default
  dropship-shared:
    external: true