# Variables

# "APP_ROOT"                           The root directory to mount for the app.
# "APP_STARTUP_CMD"                    Start-up command invoked for app service after setting up dependencies. Example "yarn dev"
# "MONGO_INITDB_ROOT_USERNAME"         The username for the root user of the auxiliary database.
# "MONGO_INITDB_ROOT_PASSWORD"         The password for the root user of the auxiliary database.

version: "3.9"

services:
  app:
    build:
      context: ./server/docker/images/app
    volumes:
      - ./${APP_ROOT}:/var/app:cached
      - data-app-node-modules:/var/app/node_modules
      - data-app-build-framework:/var/app/.next
      - data-app-themes:/var/themes
    working_dir: /var/app
    command: ${APP_STARTUP_CMD}
    networks:
      - default
      - dropship-shared
    ports:
      - 9229:9229
    depends_on:
      app-dependencies:
        condition: service_completed_successfully
    restart: unless-stopped

  app-dependencies:
    build:
      context: ./server/docker/images/app
    volumes:
      - ./${APP_ROOT}/package.json:/var/app/package.json
      - ./${APP_ROOT}/yarn.lock:/var/app/yarn.lock
      - data-app-node-modules:/var/app/node_modules
    working_dir: /var/app
    command: yarn

  color-theme-utility:
    build:
      context: ./server/docker/images/theme-server
      args:
        - COLOR_THEME_UTILITY_URL=${COLOR_THEME_UTILITY_URL}
    volumes:
      - data-app-themes:/var/themes
    networks:
      - default
    ports:
      - 8080:80

  cockpit:
    image: agentejo/cockpit:latest
    volumes:
      - data-cockpit:/var/www/html/storage
    networks:
      - default
      - dropship-shared
    environment:
      - COCKPIT_SESSION_NAME=cockpit
    restart: unless-stopped

volumes:
  data-cockpit:
    name: freytag-data-cockpit
    driver: local
  data-app-node-modules:
    name: freytag-data-app-node-modules
    driver: local
  data-app-build-framework:
    name: freytag-data-app-build-framework
    driver: local
  data-app-themes:
    name: freytag-data-app-themes
    driver: local

networks:
  default:
    name: freytag-default
  dropship-shared:
    external: true