---
# Controller
host_root: "{{ playbook_dir }}/../.."

# Server
server_user: server

server_domains: [
  {name: "augustfreytag.com", domains: "augustfreytag.com,www.augustfreytag.com"},
  {name: "cockpit.augustfreytag.com", domains: "cockpit.augustfreytag.com"}
]

# App
app_version: "master"
app_root: "/var/www/freytag"

# Dependencies
dep_swift_release: "https://swift.org/builds/swift-5.2.5-release/ubuntu1804/swift-5.2.5-RELEASE/swift-5.2.5-RELEASE-ubuntu18.04.tar.gz"
dep_listener_service: "https://gitlab.com/apricum/gitlab-listener/-/raw/master/System/gitlab-listener.service"
dep_listener_release: "http://drop.augustfreytag.com/gitlab-listener-0.5.1-linux-x86-64.tar.gz"
dep_cockpit_sync_release: "http://drop.augustfreytag.com/cockpit-sync-1.0.0-linux-x86-64.tar.gz"