---
# Controller
host_root: "{{ playbook_dir }}/../.."

# Server
server_user: server
server_shared_network: dropship_shared

# App
app_version: "feature/central-dropship"
app_root: "/var/www/freytag"
app_sub_directory: "app-next"

# Volumes
cockpit_sync_directory: "/var/www/utility/cockpit"
cockpit_sync_archive: "archive"
cockpit_docker_volume: "freytag_data_cockpit"

# Listener
listener_server_port: "8080"

# Dependencies
dep_swift_release: "https://swift.org/builds/swift-5.2.5-release/ubuntu1804/swift-5.2.5-RELEASE/swift-5.2.5-RELEASE-ubuntu18.04.tar.gz"
dep_listener_service: "https://gitlab.com/apricum/gitlab-listener/-/raw/master/System/gitlab-listener.service"
dep_listener_release: "http://drop.augustfreytag.com/gitlab-listener-0.5.2-linux-x86-64.tar.gz"
dep_cockpit_sync_release: "http://drop.augustfreytag.com/cockpit-sync-1.2.0-linux-x86-64.tar.gz"
