# Cockpit Set-Up

- name: "SERVER - Create shared Docker volume for Cockpit"
  docker_volume:
    state: present
    name: "{{ cockpit_docker_volume }}"
    driver: local
  become: yes
  tags:
    - cockpit

- name: "FILE - Set-up Cockpit sync directory"
  file:
    path: "{{ cockpit_sync_root }}/{{ cockpit_sync_archive }}"
    state: directory
    mode: "0755"
    owner: "server"
  become: yes
  tags:
    - cockpit
    - cockpit-update

- name: "DATA - Fetch most recent Cockpit state"
  git:
    repo: "https://{{ gitlab_media_deploy_user }}:{{ gitlab_media_deploy_password }}@gitlab.com/apricum/folio-freytag-media.git"
    dest: "{{ cockpit_sync_root }}/{{ cockpit_sync_archive }}"
    force: yes
  tags:
    - cockpit
    - cockpit-update

- name: "DATA - Sync Cockpit state to volume"
  command:
    chdir: "{{ cockpit_sync_root }}"
    cmd: "cockpit-sync restore --docker-volume {{ cockpit_docker_volume }} --archive ./{{ cockpit_sync_archive }}"
  become: yes
  tags:
    - cockpit
    - cockpit-update
