# Services

- name: "FILE - Create temporary directory for NGINX mounting"
  file:
    path: "{{ server_dev_tmp_directory }}"
    state: directory
  tags:
    - app-services
    - app-services-start

- name: "SERVER - Start application services"
  docker_compose:
    project_src: "{{ app_root }}"
    restarted: yes
  environment:
    APP_STARTUP_CMD: "{{ app_startup_command }}"
    COCKPIT_ACCESS_TOKEN: "{{ cockpit_access_token }}"
    COCKPIT_PROTOCOL: "{{ cockpit_protocol }}"
    COCKPIT_HOST_CLIENT: "{{ cockpit_host_client }}"
    COCKPIT_HOST_SERVER: "{{ cockpit_host_server }}"
    SERVER_NGINX_CONFIG_FILE: "{{ server_nginx_config_file }}"
    SERVER_CERTIFICATE_DIRECTORY: "{{ server_dev_tmp_directory }}"
    SERVER_CERTIFICATE_LOG_DIRECTORY: "{{ server_dev_tmp_directory }}"
  tags:
    - app-services
    - app-services-start