# Services

- name: "SERVER - Start application services"
  shell:
    cmd: "{{ app_root }}/scripts/compose.sh up -d"
  become: yes
  environment:
    live: "1"
  tags:
    - app-services
    - app-services-start
