# Services

- name: "SERVER - Stop application services"
  shell:
    cmd: "docker-compose --file {{ app_root }}/server/docker/docker-compose.yml --project-directory {{ app_root }} --env-file {{ docker_env_root }}/parameters.live.private.env down"
  become: yes
  tags:
    - app-services
    - app-services-stop