# Services

- name: "SERVER - Stop application services"
  shell:
    cmd: "{{ app_root }}/scripts/compose.sh down"
  become: yes
  environment:
    live: "1"
  ignore_errors: yes
  tags:
    - app-services
    - app-services-stop
